apiVersion: v1
kind: Service
metadata:
  name: library-svc
spec:
  type: NodePort
  selector:
    app: library-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32323
